/*
 * DCF77 Radio Clock Application for RP2040
 *
 * Copyright (C) 2023 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef DCF77_CLOCK_HPP
#define DCF77_CLOCK_HPP

#include "dcf77.hpp"
#include "gui.hpp"

class DCF77_clock
{
public:
  static void main();
private:
  static const uint16_t GPIO_I2C_SDA_PIN;
  static const uint16_t GPIO_I2C_SCL_PIN;
  static DCF77 *dcf77;
  static bool call_bit;
  static bool dst_announce;
  static bool dst;
  static uint8_t estimated_signal_quality;
  static uint64_t last_updated_wallclock_us;
  static GUI *gui;
  static void gpio_cleanup();
  static void init_i2c();
  static void init_gui();
  static void init_dcf77();
  static void receive_data(const uint64_t target_wallclock_us,
                           DCF77::time_code_t &time_code);
  static void update_display(const datetime_t datetime);
  static int8_t compare_datetime(const datetime_t &datetime1,
                                 const datetime_t &datetime2);
  static void loop();
  static void init();
  static void deinit();
};

#endif /* DCF77_CLOCK_HPP */

/*
 * Local variables:
 *   mode: c++
 *  coding: utf-8
 * End:
 */
