/*
 * DCF77 Radio Clock GUI for RP2040
 *
 * Copyright (C) 2023 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef GUI_HPP
#define GUI_HPP

#include "pico/stdlib.h"
#include "hd44780.hpp"

class GUI {
public:
  GUI();
  virtual ~GUI();
  bool init();
  void clear();
  void update(const datetime_t datetime, const bool dst, const bool call_bit);
private:
  static const uint16_t LCD_WIDTH;
  static const uint16_t LCD_LINES;
  static const HD44780::pattern_size_t LCD_DOTSIZE;
  static const uint8_t ICON_BELL[];
  static const uint8_t ICON_PHONE[];
  static const uint8_t ICON_TRIANGLE_RIGHT[];
  static const uint8_t ICON_SIGNAL_LOW[];
  static const uint8_t ICON_SIGNAL_MEDIUM[];
  static const uint8_t ICON_SIGNAL_HIGH[];
  static const char *STR_DAY_OF_THE_WEEK[7];
  HD44780_mpu_interface *lcd_mpu_interface;
  HD44780 *lcd;
  void deinit();
};

#endif /* GUI_HPP */

/*
 * Local variables:
 *   mode: c++
 *  coding: utf-8
 * End:
 */
